logging:
  level:
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
server:
  port: 8080
spring:
  r2dbc:
    properties:
      logger:
        level: DEBUG
  application:
    name: "Requests"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"


adapters:
  r2dbc:
    host: "localhost"
    port: 5433
    database: "crediya-solicitudes"
    schema: "public"
    username: "calderonjh"
    password: "securepass"